endpoints:
    file: {filename: 'data/LM399_popcorn_noise_test_{date}.csv', descriptor: "This file contains voltages of 10 LM399/ADR1399 references which are scanned using a K2002 and a SCAN2000 SSR card."}
    mqtt: {host: hal43.apq, port: 1883}
devices:
    - {uuid: 15d9f44c-03b4-465b-b596-4cb623d57199, driver: k2002_scanner, name: 0, pad: 16, timeout: 100, device_name: "K2002",
       initial_commands: [
           "*CLS",
           "*RST",
           "*OPC?",
           ":SYST:AZER:TYPE SYNC",  # azero to line sync
           ":SYST:LSYN:STAT ON",  # line sync
           ":SENS:VOLT:DC:RANGe 20; DIG 9; NPLC 10; AVERage:COUNt 2; TCONtrol REPeat; STATe ON; ADVanced:STATe OFF",
           ":SENS:VOLT:DC:AVER:STAT ON",  # Enable averaging
           ":FORM:DATA REAL,64",  # read data as bytes instead of text
           ":FORM:ELEM READing",  # only return the reading, not stuff like the channel or a timestamp
           ":FORM:EXP HPR",  # Needs FW > A06, possibly A09
           ":INITiate:CONTinuous OFF; :ABORt",  # disable continuous initiation and place K2002 in idle
           ":ROUTE:SCAN:LSEL INT",  # Enable the internal scanner card
           ":INITiate:CONTinuous ON",  # Enable continuous triggering
       ],
       post_read_commands: [],
       active_channels: [0,1,2,3,4,5,6,7,8,9],
       base_topic: "sensors/room_011/LM399/k2002"
      }
    - {uuid: 803045a8-1c74-4e02-b9b7-232f3ad77be7, driver: fluke1524, tty: "/dev/ttyUSB1", timeout: 1, baudrate: 9600, device_name: "temperature", column_names: ["Temperature 10k Thermistor (PCB)", "Temperature PT100 (Room)"], base_topic: "sensors/room_011/LM399/fluke1524"}
    - {uuid: 7ea1048c-eaad-42cf-aff9-ab69c69eb0ee, driver: ee07, tty: "/dev/ttyACM0", timeout: 0.5, baudrate: 115200, device_name: "EE07 humidity probe", column_names: ["Humidity (Ambient)", "Temperature humidity sensor (Ambient)"], base_topic: "sensors/room_011/LM399/ee07"}
    - {uuid: c9e5e997-6db6-42ec-90ea-70052a091ea0, driver: ldt5948, tty: "/dev/ttyUSB0", timeout: 0.5, baudrate: 115200, device_name: "ILX temperature controller", column_names: ["Temperature in loop", "TEC current", "TEC voltage", "Temperature setpoint"], base_topic: "sensors/room_011/LM399/ldt5948"}
